version: "3.5"
networks:
    heimdall-api-dev-network:
        name: heimdall-api-dev-network
services:
    db-mysql-dev:
        container_name: heimdall-api-dev-db
        image: mysql:latest
        command: --init-file /usr/src/app/init.sql
        volumes:
            - ./mysql/init.sql:/usr/src/app/init.sql
            - ./volumes/db:/var/lib/mysql
        expose:
            - "3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: <PASSWORD>
            MYSQL_DATABASE: <DATABASE_NAME>
            MYSQL_USER: <USER>
            MYSQL_PASSWORD: <PASSWORD>
        networks:
            - heimdall-api-dev-network

    heimdall-api-dev:
        container_name: heimdall-api-dev
        build:
            context: ./api
            dockerfile: Dockerfile.dev
        image: treed1104/heimdall-api-dev:latest
        restart: always
        links:
            - db-mysql
        expose:
            - "5000:5000"
        networks:
            - heimdall-api-dev-network
