version: "3.5"
networks:
    heimdall-api-network:
        name: heimdall-api-network
services:
    nginx:
        container_name: heimdall-api-nginx
        image: nginx:latest
        restart: always
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
            - 443:443
        networks:
            - heimdall-api-network

    db-mysql:
        container_name: heimdall-api-db
        image: mysql:latest
        command: --init-file /usr/src/app/init.sql
        volumes:
            - ./mysql/init.sql:/usr/src/app/init.sql
            - ./volumes/db:/var/lib/mysql
        expose:
            - "3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: <PASSWORD>
            MYSQL_DATABASE: <DATABASE_NAME>
            MYSQL_USER: <USER>
            MYSQL_PASSWORD: <PASSWORD>
        networks:
            - heimdall-api-network

    heimdall-api:
        container_name: heimdall-api
        build:
            context: ./api
            dockerfile: Dockerfile
        image: treed1104/heimdall-api:latest
        restart: always
        links:
            - db-mysql
        expose:
            - "5000"
        networks:
            - heimdall-api-network
